language: node_js
node_js:
  - "5.1"
compiler: gcc
env: 
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8
      - g++-4.8
before_install:		
  - rvm install 2.2.5
  - nvm --version
  - node --version
  - npm --version
  - gcc --version
  - g++ --version
install:
  - npm install
  - npm install -g ember-cli
  - npm install -g bower
  - npm install -g nodeunit
  - ember -v
  - cd frontend && npm install && cd ../
  - cd frontend && bower install && cd ../
script:
  - mkdir dist && cd dist && npm pack ../ && cd ..
  - ls -al frontend/dist/assets
after_script:
  - nodeunit tests
  - node main.js & cd frontend && ember test && cd ..
deploy:
  provider: s3
  access_key_id: "AKIAIHYANWLHBG5FRLZQ"
  secret_access_key:
    secure: "YMpt4DcyoT/zAz+ym0ZWrDutp/7NlXUlSAn6ZVXXIF16tYX+Dw3WSsk4ZE3M6/rHRLUZzmJ5IzC6tTkBgeuRUdz9fukVcm1IlJb2TqGESzkTEKCeuelAIFAgFsdw8WBhFxbEh8YIvuHop/0V8KVpbgCv4B8cDHisvjwT8ukiiMbROTFp7idsbED9ySzgRQk2ovss07QtEgv+OCBPFvzldgMTebDrzvfVeRogPiZqL/d+NsbSAQgOhDb0YQmQJJ3VGNjhwbF/dSuEUZ8zfim7YJxpmVEpmmfkrFvKaBy4ACuqaopf3S6QQH0Afy8so22TJBnPAGRaTraecF+mwYaRKz8ih0Yqx06rRBRXQM0kmYjVKcXCbIlOUysYc4tuN4tCRgzMtU2XEUykq1IR0mNKRXukC1O8ZYsBDkMB+oy6mSbQxX+WIQsGeR6+Ve8ItdM6CoQF52kDTBY/8Jp1IZRB6rj6OSnxEqpobngKKhh+VlYhwXkSsod9EsDrxgA2CrlcIfK5wdoBL2PIauUGCxw+q4e94AMCcvbO6GLQQdp0CQCvPEEujyxoB7Ibe9cvNAfL94h8Hxt5X3pM85aTY5+q7B9nkrgUnTT4SiuZurn6X6dHIoWqH3DUMzJmuBCx0dsF1SHiSJK0mHRkUpCoqU5bwABmiJgFJiUZuXncsK/2UjA="
  bucket: "remote-mediaserver"
  skip_cleanup: true
  acl: public_read
  local_dir: dist
  region: eu-west-1
  upload-dir: ${TRAVIS_BRANCH}
  on:
    all_branches: true
