language: node_js
node_js:
  - "6.10.2"
compiler: gcc
env: 
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8
      - g++-4.8
before_install:		
  - rvm install 2.2.5
  - nvm --version
  - node --version
  - npm --version
  - gcc --version
  - g++ --version
install:
  - npm install -g ember-cli
  - npm install -g bower
  - npm install -g nodeunit
  - npm install -g jshint
  - cd frontend && npm install && cd ../
  - cd frontend && bower install && cd ../
  - npm install
  - ember -v
script:
  - jshint --show-non-errors --verbose --config .jshintrc backend/
  - nodeunit tests
  - node main.js & cd frontend && ember test --environment=ci && cd ..
  - mkdir dist
  - cd dist && npm pack ../ && cd ..
deploy:
  provider: s3
  access_key_id: "AKIAIHYANWLHBG5FRLZQ"
  secret_access_key:
    secure: "emKpIuz1yAXcg4/5vGC5/DllUFu3G0k56lnZS8ThlZfKlrZnwCwSQKzhyaFX5GOB+6ARTgYT0nkdr64bFwJLduFHvVv4kgKY5edR3PC5VDDTY1qdnw8WU7QSkpTZ+BiB0SpBY0R3Q3Ox1JSgYlAWCH80vsqt7LawyOuK6wmOQne3jshaHXIMh5bG+vPxhU+52p8KVmZRTZIb22WfWtySHAKtQyZE/yHzw0R7apxoBZ/Xus9aX2M8CD8z4i7b0BN87eeOYTX4V6j56BYEizDuMgZGvAn34IzNcGBmbM9r94Xbu7i0RH4xDKYN4EyAapFQK6AW0M2B3Nd/uveHiRAVj4ALKVeg16VCVaveNcoCOaczw4trZTh5MTRqWaTIM7JeVni5Kc4+2II5fBg5uVSNiZW/991WKusIr32enAqGOm2SCneG6LAd4qm5mvvOLIuL3u7p8qjHCcSdVkDN839HpqfQ+efZ81ty5r1J8FjUn0gKGQiBRYdbv+wFFCcECe9zBv5XZVJ+8RduGjtqRno681sDbMmE3A5bipNE11vf/bmIRuj/ufQDkOmomHbIjNzvOvun01eOC79tPTwJrhZm1C+9PpjTLQzoULq49nTLK+elZuwusoJiLfQlgep/wWIBuZYf6MTMwl/yYk/ElLVM/qW3Z9USrEozcwRdlCbJByo="
  bucket: "remote-mediaserver"
  skip_cleanup: true
  acl: public_read
  local_dir: dist
  region: eu-west-1
  upload-dir: ${TRAVIS_BRANCH}
  on:
    all_branches: true
