version: '3.4'

services:
########################
## remote-MediaServer ##
########################
  app:
    build: .
    restart: always
    ports:
      - "8234:8234"
      - "8235:8235"
    volumes:
      - "./data:./.remote"
